In [5]:
import numpy as np

array = np.array([
    [
        ['A', 'B', 'C'],
        ['D', 'E', 'F'],
        ['G', 'H', 'I']
    ],
    [
        ['J', 'K', 'L'],
        ['M', 'N', 'O'],
        ['P', 'Q', 'R']
    ],
    [
        ['S', 'T', 'U'],
        ['V', 'W', 'X'],
        ['Y', 'Z', '']
    ]
])

print(array[2, 2, 0])

Y


In [14]:

array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

# print(array[:2:2] )
print(array[0,:])

[1 2 3 4]


In [19]:
ages = np.array([[21,22,23,24,25,26,27],
                [39,55,15,99,18,19,20]])
teenagers = ages[ages<18]
adult = np.where(ages<18,ages,0)
a = np.where(ages<18,1,0)
print(teenagers)
print(adult)
print(a)

[15]
[[ 0  0  0  0  0  0  0]
 [ 0  0 15  0  0  0  0]]
[[0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0]]


In [71]:
rng = np.random.default_rng(seed = 1)
print(rng.integers(1,101,size=(3)))
print(np.random.uniform(1,101,size=(3)))

[48 52 76]
[65.28217584  9.39558559 55.10486527]


In [ ]:
import pandas as pd

df = pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\data.csv",index_col="Name")
print(df.to_string())

             No     Type1     Type2  Height  Weight  Legendary
Name                                                          
Bulbasaur     1     Grass    Poison     0.7     6.9          0
Ivysaur       2     Grass    Poison     1.0    13.0          0
Venusaur      3     Grass    Poison     2.0   100.0          0
Charmander    4      Fire       NaN     0.6     8.5          0
Charmeleon    5      Fire       NaN     1.1    19.0          0
Charizard     6      Fire    Flying     1.7    90.5          0
Squirtle      7     Water       NaN     0.5     9.0          0
Wartortle     8     Water       NaN     1.0    22.5          0
Blastoise     9     Water       NaN     1.6    85.5          0
Caterpie     10       Bug       NaN     0.3     2.9          0
Metapod      11       Bug       NaN     0.7     9.9          0
Butterfree   12       Bug    Flying     1.1    32.0          0
Weedle       13       Bug    Poison     0.3     3.2          0
Kakuna       14       Bug    Poison     0.6    10.0    

In [ ]:

# print(df["Name"].to_string())
# print(df["Height"].to_string())
# print(df["Weight"].to_string())
print(df[["Weight","Name","Height"]].to_string())



     Weight        Name  Height
0       6.9   Bulbasaur     0.7
1      13.0     Ivysaur     1.0
2     100.0    Venusaur     2.0
3       8.5  Charmander     0.6
4      19.0  Charmeleon     1.1
5      90.5   Charizard     1.7
6       9.0    Squirtle     0.5
7      22.5   Wartortle     1.0
8      85.5   Blastoise     1.6
9       2.9    Caterpie     0.3
10      9.9     Metapod     0.7
11     32.0  Butterfree     1.1
12      3.2      Weedle     0.3
13     10.0      Kakuna     0.6
14     29.5    Beedrill     1.0
15      1.8      Pidgey     0.3
16     30.0   Pidgeotto     1.1
17     39.5     Pidgeot     1.5
18      3.5     Rattata     0.3
19     18.5    Raticate     0.7
20      2.0     Spearow     0.3
21     38.0      Fearow     1.2
22      6.9       Ekans     2.0
23     65.0       Arbok     3.5
24      6.0     Pikachu     0.4
25     30.0      Raichu     0.8
26     12.0   Sandshrew     0.6
27     29.5   Sandslash     1.0
28      7.0    Nidoran♀     0.4
29     20.0    Nidorina     0.8
30     6

In [10]:
#SELECTION BY ROW/S

print(df.loc["Pikachu"])

No                 25
Type1        Electric
Type2             NaN
Height            0.4
Weight            6.0
Legendary           0
Name: Pikachu, dtype: object


In [14]:
pokemon = input("Enter the name of the pokemon: ")

try:
    print(df.loc[pokemon])
except KeyError:
    print("Pokemon not found in the dataset.")

No                 25
Type1        Electric
Type2             NaN
Height            0.4
Weight            6.0
Legendary           0
Name: Pikachu, dtype: object


In [17]:
group = df.groupby("Type1")
print(group["Height"].mean())

Type1
Bug         0.900000
Dragon      2.666667
Electric    0.855556
Fairy       0.950000
Fighting    1.185714
Fire        1.216667
Ghost       1.466667
Grass       1.083333
Ground      0.850000
Ice         1.550000
Normal      0.986364
Poison      1.221429
Psychic     1.371429
Rock        1.844444
Water       1.300000
Name: Height, dtype: float64
