In [5]:
import numpy as np

array = np.array([
    [
        ['A', 'B', 'C'],
        ['D', 'E', 'F'],
        ['G', 'H', 'I']
    ],
    [
        ['J', 'K', 'L'],
        ['M', 'N', 'O'],
        ['P', 'Q', 'R']
    ],
    [
        ['S', 'T', 'U'],
        ['V', 'W', 'X'],
        ['Y', 'Z', '']
    ]
])

print(array[2, 2, 0])

Y


In [14]:

array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

# print(array[:2:2] )
print(array[0,:])

[1 2 3 4]


In [19]:
ages = np.array([[21,22,23,24,25,26,27],
                [39,55,15,99,18,19,20]])
teenagers = ages[ages<18]
adult = np.where(ages<18,ages,0)
a = np.where(ages<18,1,0)
print(teenagers)
print(adult)
print(a)

[15]
[[ 0  0  0  0  0  0  0]
 [ 0  0 15  0  0  0  0]]
[[0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0]]


In [71]:
rng = np.random.default_rng(seed = 1)
print(rng.integers(1,101,size=(3)))
print(np.random.uniform(1,101,size=(3)))

[48 52 76]
[65.28217584  9.39558559 55.10486527]
