In [1]:
import numpy as np
print(np.__version__)


2.1.3


In [3]:
v1  = np.array([10,6,7])
v2  = np.array([3,5,12])
v3 = np.array(5)
print(v1)
print(v2)
# print(v1.ndim)
print(v1.shape)

[10  6  7]
[ 3  5 12]
(3,)


In [14]:
class Student:
    def __init__(self, name , age)->None:
        self._name = name
        self.age = age
    @property
    def name(self):
        return f"{self.name}"

In [16]:
s1 = Student("Moaz",20)
s1.name()

RecursionError: maximum recursion depth exceeded

In [ ]:
vec = np.array([1,2,3,4])
mat = vec[:,None]

In [17]:
def array_reshape(arr,row =-1,cols =-1):
    try:
        arr = np.array(arr)
        return arr.reshape((row,cols))
    except Exception as e:
        raise ValueError(f"Invalid Reshape Operation:{e}")

In [18]:
vec =[1,2,3,4,5,6]
print("test1(2*3 matrix): ",array_reshape(vec ,2,3))

test1(2*3 matrix):  [[1 2 3]
 [4 5 6]]


In [ ]:
mat = np.array([[5, 2, 6],
                [4, 5, True]])

fmat = mat.astype(str)

print(fmat)
print(fmat.dtype)

In [ ]:
m = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [0, 0, 0]])

m[-1:3, 0:2]

In [5]:
import numpy as np
my_list =[1,2,3,4]
my_list = my_list *2
print(my_list)

array = np.array([1,2,3,4])
array *= 2
print(array)
print(type(array))

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]
<class 'numpy.ndarray'>


In [ ]:
array1 = np.array('A') # Zero Linear
array2 = np.array(['A','B','C','D']) # one Dimentional array
array3 =np.array(
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
) #2_D Array
