# NumPy Programming Assignment

Part 1: Smart Array Factory
Task: Create a function that allows students to generate specific array types quickly using built-in NumPy methods.


In [ ]:
import numpy as np


def array_factory(mode, shape, value=None):
    """
    Creates various NumPy arrays based on the mode.

    Modes:
    - 'zeros'    : Array filled with 0.
    - 'ones'     : Array filled with 1.
    - 'full'     : Array filled with a specified value.
    - 'identity' : A square identity matrix.
    """

    mode = mode.lower()

    if mode == "zeros":
        return np.zeros(shape)

    elif mode == "ones":
        return np.ones(shape)

    elif mode == "full":
        if value is None:
            raise ValueError("Value must be provided for 'full' mode.")
        return np.full(shape, value)

    elif mode == "identity":
        if isinstance(shape, int):
            return np.eye(shape)

        elif len(shape) == 2 and shape[0] == shape[1]:
            return np.eye(shape[0])

        else:
            raise ValueError(
                "For 'identity' mode, shape must be a square matrix."
            )

    else:
        raise ValueError(
            "Invalid mode. Choose from: 'zeros', 'ones', 'full', 'identity'."
        )


arr1 = array_factory("zeros", (2, 3))
print("Zeros:")
print(arr1)


arr2 = array_factory("ones", (2, 3))
print("\nOnes:")
print(arr2)

arr3 = array_factory("full", (2, 3), 7)
print("\nFull:")
print(arr3)


arr4 = array_factory("identity", 4)
print("\nIdentity:")
print(arr4)

Zeros:
[[0. 0. 0.]
 [0. 0. 0.]]

Ones:
[[1. 1. 1.]
 [1. 1. 1.]]

Full:
[[7 7 7]
 [7 7 7]]

Identity:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Part 2: The secure_reshape_and_stack Function.

This function demonstrates how to handle data integration by transforming a flat data structure into a matrix and then combining it with an existing dataset

In [2]:
import numpy as np

def secure_reshape_and_stack(data1, data2, new_shape):
    """
    1. Validates and converts inputs to NumPy arrays.
    2. Reshapes the first dataset to a specific dimension.
    3. Vertically stacks both datasets into one matrix.
    """
    try:
        arr1 = np.array(data1)
        arr2 = np.array(data2)

        reshaped_arr1 = arr1.reshape(new_shape)

        combined_dataset = np.vstack((reshaped_arr1, arr2))

        return combined_dataset

    except ValueError as e:
        raise ValueError(f"Company-grade Error: {e}")

part-3 The apply_threshold Function.

This function demonstrates Conditional Access and Modification, which are primarily used in data cleaning and processing. It follows the logic of identifying specific elements based on a boolean condition and replacing them efficiently.

In [4]:
def apply_threshold(arr, threshold, replacement_value=-1):
    """
    Finds elements satisfying a condition (>= threshold)
    and replaces them with a new value.
    """
    arr = np.array(arr)

    condition = arr >= threshold

    modified_arr = np.where(condition, replacement_value, arr)

    return modified_arr

TestCase

In [9]:
# Regional Branch A (Flat sales data)
branch_a = [1, 2, 3, 4, 5, 6] 

# Regional Branch B (Already formatted 2x3 matrix)
branch_b = [[7, 8, 9], 
            [10, 11, 12]]

# Reshape A to 2x3 and stack with B
final_report = apply_threshold(branch_a, branch_b, (2, 3))
print(final_report)
# Resulting shape: (4, 3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
v= np.array([1,2,3])
apply_threshold(v,2,-20)


array([  1, -20, -20])